version: '3.8'

services:
  # 🔹 Reverse proxy Traefik pour gérer les requêtes et le SSL
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=ethan.soudry-ort.online"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-data:/letsencrypt

  # 🔹 Service ReactJS
  app:
    container_name: react-app
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`ethan.soudry-ort.online`)"
      - "traefik.http.routers.react.entrypoints=websecure"
      - "traefik.http.routers.react.tls.certresolver=letsencrypt"
      - "traefik.http.services.react.loadbalancer.server.port=3000"

  # 🔹 Base de données PostgreSQL avec backup automatique
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup:/backup
    labels:
      - "traefik.enable=false"
    command: ["bash", "-c", "exec postgres"]

volumes:
  pgdata:
  traefik-data:
