version: '3.8'

services:
  # 🔹 Reverse proxy Traefik pour gérer les requêtes et le SSL
  traefik:
    image: traefik:v2.9
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      # - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # - "--certificatesresolvers.letsencrypt.acme.email=ethan.soudry-ort.online"
      # - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ".:/etc/traefik"

  # 🔹 Service ReactJS
  app:
    container_name: react-app
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`ethan.soudry-ort.online`)"
      - "traefik.http.routers.react.entrypoints=web"
      # - "traefik.http.routers.react.tls.certresolver=letsencrypt"
      - "traefik.http.services.react.loadbalancer.server.port=3000"
