stages:
  - deploy

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Mise à jour des paquets..."
    - sudo apt update -y && sudo apt upgrade -y
    - echo "Installation d'OpenSSH client..."
    - sudo apt install -y openssh-client
    - echo "Configuration de la clé SSH..."
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - echo "Ajout de l'hôte au fichier known_hosts..."
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    - echo "Connexion et déploiement..."
    - ssh $EC2_USER@$EC2_HOST "cd /chemin/du/projet && git pull origin main && exit"
    - echo "Nettoyage..."
    - rm -rf ~/.ssh
